### ISSUE TITLE
Release com_github_aignas_rules_shellcheck to bzlmod

### ISSUE THREAD

**Issue by luispadron** [aignas/rules_shellcheck#21]
Hi! I noticed the `MODULE.bazel` but don't see any release in https://registry.bazel.build/all-modules could we get this added to the registry?

**Comment by keith** [comment]
Looks like ideally there would be a new release first so we didn't have to pin to a commit in the BCR, but otherwise anyone can add it now

**Comment by aignas** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/1059
