### ISSUE TITLE
Create a new release to include shellcheck version update

### ISSUE THREAD

**Issue by anthonyjpratti** [aignas/rules_shellcheck#22]
A release that incorporates #19 would allow folks to remove any custom patches they have upgrading the version.

Aside, it might be worth considering allowing end users to configure there own versions or download paths. 
Examples:
- [rules_js](https://bazelbuild.github.io/rules_nodejs/install.html)
- [rules_go go_register_toolchains](https://github.com/bazelbuild/rules_go/blob/09a206c823bc1fdb887d458677a5ff1953be5b81/go/toolchains.rst#go-register-toolchains)
- [rules_go go_download_sdk](https://github.com/bazelbuild/rules_go/blob/09a206c823bc1fdb887d458677a5ff1953be5b81/go/toolchains.rst#go-download-sdk)

More than happy to help!

**Comment by luispadron** [comment]
@aignas Do you have a few minutes, or if you'd like to add other maintainers to the project to handle this that works too!

This issue and #21 would be great
