### ISSUE TITLE
`shellcheck` rule seems to create a file with the binary path in it

### ISSUE THREAD

**Issue by phlax** [aignas/rules_shellcheck#5]
I tried following the docs for this repo, and added the following:

```starlark

load("//:def.bzl", "shellcheck")

shellcheck(name = "shellcheck")

```
when i then tried to run with the following 

```console

$ bazel run //:shellcheck -- -x /path/to/my/sh/file

```

it ignores all of the arguments and always just prints the help

with the following `BUILD`:

```starlark

load("//:def.bzl", "shellcheck")

shellcheck(name = "shellcheck_path")

sh_binary(
    name = "shellcheck",
    data = [":shellcheck_path"],
    srcs = ["run_shellcheck.sh"],
    args = [
        "$(location //:shellcheck_path)",
    ]
)

```

and a sh wrapper like so:

```bash

#!/bin/bash

SHELLCHECK_SCRIPT_PATH="${1}"
shift
SHELLCHECK_PATH="$(cat "$SHELLCHECK_SCRIPT_PATH")"

exec "$SHELLCHECK_PATH" "$@"

```

it works as expected

not sure if i am mis understanding/configuring something, and whether my hack is necessary

**Comment by keith** [comment]
Here's a potential fix for this https://github.com/aignas/rules_shellcheck/pull/6

**Comment by aignas** [comment]
@phlax, let me know if you are still seeing the issue on the latest master and thanks @keith for the PR in attempt to fix this.
